# Site settings
title: "Informatics"
email: "informatics@mitpu.org"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.;w

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true

